## PREPARACION DE LOS DATOS

In [1]:
# Importacion de librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import io

# import pyeto library
import pyeto

# import datetime
import datetime

# Determinar numero de dias en year/month
from calendar import monthrange

# Apagamos algunos mensajes de warning
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
def rad_solar_from_temp(year, month, day, latitude, longitude, altitude, coastal, temp_min, temp_max):
    # calculate dia of the anio
    day_of_year = datetime.date(year,month,day).timetuple().tm_yday
    
    # pre-calculus data for estimating solar radiation from temperatures 
    # latitude conversion from degrees to radians
    latitude_rad = pyeto.deg2rad(latitude)

    # longitude conversion from degrees to radians
    longitude_rad = pyeto.deg2rad(longitude)

    # calculate solar declination from dia of the anio
    sol_dec = pyeto.sol_dec(day_of_year)

    # calculate sunset hour angle (Ws) from latitude and solar declination
    sha = pyeto.sunset_hour_angle(latitude_rad, sol_dec)

    # calculate the inverse relative distance between earth and sun from dia of the anio.
    ird = pyeto.inv_rel_dist_earth_sun(day_of_year)

    # estimate daily extraterrestrial radiation (Ra, ‘top of the atmosphere radiation’).
    et_rad = pyeto.et_rad(latitude_rad, sol_dec, sha, ird)

    # estimate clear sky radiation from altitude and extraterrestrial radiation
    cs_rad = pyeto.cs_rad(altitude, et_rad)
    
    # Estimate incoming solar (or shortwave) radiation, Rs,from min and max temperature 
    rad_sol_from_t = pyeto.sol_rad_from_t(et_rad, cs_rad, temp_min, temp_max, coastal)
    
    return rad_sol_from_t

In [3]:
# Funcion para generar los archivos correspondiente a los meses especificados como requerimiento para calculo ET0
def data_req_for_et0(conagua_year_data, month_list, year, latitude, longitude, altitude, coastal, export_file):
    ###########################################################################################################
    xls = pd.ExcelFile(conagua_year_data)
    
    for month in month_list:
        # Creación del dataframe a partir del archivo excel provisto usando el tab del mes
        conagua_df = pd.read_excel(xls, month)
        
        # Renombrado de encabezado de columnas de mayusculas a minusculas
        conagua_df.columns = [col.lower() for col in conagua_df]

        # Renombrado de encabezados de columnas principales para eliminar sus acronimos
        conagua_df.rename(columns={
                                    't.s': 'termometro seco', 
                                    't.h': 'termometro humedo',
                                    't.v': 'tension de vapor',
                                    'max': 'temperatura maxima',
                                    'min': 'temperatura minima',
                                    'p.r': 'punto de rocio',
                                    'h.r': 'humedad relativa',
                                    'max.1': 'humedad maxima',
                                    'min.1': 'humedad minima',
                                    'psen':'presion de la estacion',
                                    'max.2': 'presion de la estacion maxima',
                                    'min.2': 'presion de la estacion minima',
                                    'prnm':'presion residual al nivel del mar',
                                    'max.3': 'presion residual al nivel del mar maxima',
                                    'min.3': 'presion residual al nivel del mar minima',
                                    'max.4': 'evaporacion maxima',
                                    'min.4': 'evaporacion minima',
                                    'direcc': 'direccion dominante',
                                    'vel' : 'velocidad dominante',
                                    'direcc.1' : 'direcciom maxima',
                                    'vel.1' : 'velocidad maxima',
                                    'media' : 'velocidad media'
        }, inplace=True)
        ###########################################################################################################
        # Definicion de lista que contiene las columnas dentro de conagua_df
        columns_conagua_df = list(conagua_df.columns)
        
        #Definimos la lista que contiene el nombre de las columnas preservar dentro de conagua_df
        columns_remaining = [
                                    'dia',
                                    'tension de vapor',
                                    'temperatura maxima',
                                    'temperatura minima',
                                    'humedad relativa',
                                    'humedad minima',
                                    'humedad maxima',
                                    'inten',
                                    'velocidad dominante',
                                    'presion de la estacion'
        ]

        # A traves de la funcion set realizamos la substraccion
        # Cada elemento de columns_conagua_df se buscara dentro de columns_remaining
        # Si no se encuentra coincidencia alguna esta se guarda como elemento de columns_to_drop
        columns_to_drop_set = set(columns_conagua_df)-set(columns_remaining)
        columns_to_drop = sorted(columns_to_drop_set, key = lambda k : columns_conagua_df.index(k))

        # Removemos columns_to_drop de conagua_df y guardamos en conagua_df
        conagua_df.drop(columns=columns_to_drop,inplace=True)
        ###########################################################################################################
        # https://eto.readthedocs.io/en/latest/package_references.html
        # Renombramiento de columnas necesarias para calculacion de ET0 
        conagua_df.rename(columns={
                                    'tension de vapor': 'e_a',
                                    'temperatura maxima': 'T_max', 
                                    'temperatura minima': 'T_min',
                                    'humedad relativa': 'RH_mean',
                                    'humedad minima': 'RH_min',
                                    'humedad maxima': 'RH_max',
                                    'inten': 'n_sun',
                                    'velocidad dominante': 'U_z',
                                    'presion de la estacion': 'P'
        }, inplace=True)
        ###########################################################################################################
        # Generamos una nueva columna la cual tiene como proposito hacer una copia directa
        # de la columna dia a dia_index para ser usada como indice del dataframe
        conagua_df['dia_index'] = ''
        conagua_df['dia_index'] = conagua_df['dia']

        # Seteando el index en conagua_df para la columna dia_index
        conagua_df.set_index('dia_index', inplace = True)

        # Calcular dias disponibles en el mes para acotar los contenidos extras a la tabla de referencia Conagua
        # Obtencion de numeros de dias en el mes a evaluar
        monthrange_result = monthrange(year,month) 
        weekday_of_first_day_of_month = monthrange_result[0]
        number_of_days_in_month = monthrange_result[1]

        # Obtencion de columnas y renglones en conagua_df
        conagua_rows, conagua_columns = conagua_df.shape
        conagua_df = conagua_df.iloc[1:number_of_days_in_month+1]

        # Remplazamor cualquier 0 tipo int/string por Nan 
        conagua_df[conagua_df.columns] = conagua_df[conagua_df.columns].replace({'0':np.nan, 0:np.nan})

        # OBtenemos informaacion del total de valores nulos presentes en conagua_df
        conagua_isnull = conagua_df.isnull().sum()

        # Lista de columnas con valores NaN presentes 
        conagua_columns_isnull = list(conagua_isnull.index.values.tolist())

        # Definicion de lista vacia con informacion de las columnas a remover que tengan un valor NaN
        conagua_columns_nan = []

        # Checamos que columnas cuentan con valores nulos y lo agregamos a conagua_columns_dropna
        for i in range(0,len(conagua_isnull)):
            if conagua_isnull[conagua_columns_isnull[i]] > 0:
                conagua_columns_nan.append(conagua_columns_isnull[i])

        # Realizamos la imputacion de aquellos valores NaN en la columna tomando el valor anterior
        for each in conagua_columns_nan:
            conagua_df[each].fillna(method = 'ffill', inplace = True) 
        ###########################################################################################################
        # Creacion de la columna date a partir de concatenar anio/mes/dia 
        conagua_df['date'] = ''

        for i in range(conagua_df['dia'][1],len(conagua_df['dia'])+1):
            print(conagua_df['dia'][i])
            print(str(year)+'-'+str(month)+'-'+str(conagua_df['dia'][i]))
            conagua_df['date'][i] = str(year)+'-'+str(month)+'-'+str(conagua_df['dia'][i])

        #Conversión de la columna "date" al formato de serie de tiempo
        conagua_df['date'] = pd.to_datetime(conagua_df['date'])
        ###########################################################################################################
        # Hacemos una inspeccion para la seccion de temperaturas diarias
        # garantizando que la T_max sea mayor que la T_min
        # En caso de no cumplirse se invertiran los valores
        # y evitar problemas en el apartado del calculo de radiacion solar. 
        for day in conagua_df['dia']:
            #print(day,conagua_df['T_min'][day],conagua_df['T_max'][day])
            if (conagua_df['T_max'][day] < conagua_df['T_min'][day]):
                temp_t_max = conagua_df['T_max'][day]
                temp_t_min = conagua_df['T_min'][day]
                conagua_df['T_max'][day] = temp_t_min
                conagua_df['T_min'][day] = temp_t_max
        ###########################################################################################################        
        # Agregando columna para depositar valores calculados de Radiacion Solar a partir de Temperaturas
        conagua_df['R_s'] = ''        
        
        # Anadimos para cada registro de la tabla su radiacion solar a partir de temperaturas
        for day in conagua_df['dia']: 
            conagua_df['R_s'][day] = rad_solar_from_temp(year,month_list.index(month)+1,day,latitude,longitude,altitude,coastal,conagua_df['T_min'][day],conagua_df['T_max'][day])
        ###########################################################################################################
        # Arreglamos cualquier error producido por datos tipo flotante en columna de radiacion solar
        conagua_df['R_s'] = conagua_df['R_s'].astype(float, errors = 'raise')

        # Conversion de Hecto Pascales a Kilo Pascales en tension de vapor
        #1 hectopascal [hPa] = 0.1 kilopascal [kPa]
        conagua_df['e_a'] = conagua_df['e_a']*0.1

        # Conversion de Hecto Pascales a Kilo Pascales en presion de la estacion
        conagua_df['P'] = conagua_df['P']*0.1
        ###########################################################################################################
        # Eliminacion de la columna dia
        conagua_df.drop(columns=['dia'],inplace=True)

        # Seteando el index para la columna dia
        conagua_df.set_index('date', inplace = True)
        
        # Redondeamos todos los valores de los parametros a 2 decimales
        conagua_df[conagua_df.columns] = conagua_df[conagua_df.columns].round(2)

        # Guardado del Archivo en formato CSV
        if(export_file == True):
            conagua_df.to_csv('../output/conagua_' + str(year) + '_' + month.lower() + '_req_for_et0.csv')

        elif(export_file == False):
            print("Datos Conagua %s-%s" %(month,year))
            print(conagua_df)

In [4]:
# Localizacion del archivo de Conagua que contempla los datos climatologicos de un anio completo
conagua_year_data = '../datos/conagua/clima_2019.xlsx'

# Definicion de anio para busqueda de archivo de conagua con datos 
year = 2019

# Meses a preparar en resumen de datos
#month_list=['ENERO','FEBRERO','MARZO','ABRIL','MAYO','JUNIO','JULIO','AGOSTO','SEPTIEMBRE','OCTUBRE','NOVIEMBRE ']
month_list=['FEBRERO']

# Definicion de latitud, longitude, altitude, coastal para la seccion del calculo de R_s 
# latitude in degrees
latitude = 19.59216667

# longitud in degrees
longitude = -103.59075

# altitude in meters
altitude = 1408.99

# coastal – True if site is a coastal location, situated on or adjacent to coast of a large land mass 
coastal = False

# save file
export_file = False

# Llamar a funcion para preparar los datos de cada mes
data_req_for_et0(conagua_year_data, month_list, year, latitude, longitude, altitude, coastal, export_file)

La columna dia tiene valores nulos 12
La columna e_a tiene valores nulos 9
La columna T_max tiene valores nulos 9
La columna T_min tiene valores nulos 9
La columna RH_mean tiene valores nulos 9
La columna RH_max tiene valores nulos 9
La columna RH_min tiene valores nulos 9
La columna P tiene valores nulos 9
La columna U_z tiene valores nulos 9
La columna n_sun tiene valores nulos 9
Datos Conagua FEBRERO-2019
             e_a  T_max  T_min  RH_mean  RH_max  RH_min      P  U_z  n_sun  \
date
2019-01-01  1.05   11.6    9.3     59.0    98.0    31.0  85.21  2.5    3.0
2019-01-02  0.99   10.4    9.5     79.0    99.0    41.0  85.23  0.6    2.4
2019-01-03  0.88    9.6    6.9     70.0    95.0    22.0  85.12  1.5    1.0
2019-01-04  0.73    8.9    5.4     44.0    92.0    15.0  85.03  2.6    1.0
2019-01-05  0.89   11.4    6.9     49.0    92.0    18.0  85.04  2.3    2.0
2019-01-06  0.94   11.4    6.5     50.0    95.0    17.0  85.07  3.2    4.0
2019-01-07  0.97   10.9    8.0     51.0    95.0    20.0  85.05  2.8    3.5
2019-01-08  1.05   12.8    9.1     51.0    89.0    25.0  85.11  3.3    5.0
2019-01-09  1.25   13.5   11.2     71.0    94.0    37.0  85.34  0.8    8.0
2019-01-10  1.26   13.1   12.4     74.0    96.0    39.0  85.30  2.9    7.0
2019-01-11  1.21   13.3    9.1     66.0    96.0    27.0  85.14  2.9    7.0
2019-01-12  1.10   12.8    9.2     51.0    96.0    25.0  85.01  2.9    6.6
2019-01-13  1.17   14.7    9.9     56.0    96.0    28.0  85.17  4.3    7.0
2019-01-14  1.10   12.5    8.7     56.0    98.0    24.0  85.16  2.5    5.2
2019-01-15  1.00   12.0    8.3     50.0    98.0    21.0  85.05  1.8    5.0
2019-01-16  1.10   12.1    9.7     71.0    98.0    30.0  85.04  1.0    5.2
2019-01-17  1.06   11.9    8.7     67.0    96.0    26.0  85.13  1.0    5.0
2019-01-18  1.05   11.5    9.4     59.0    98.0    25.0  85.10  3.2    4.0
2019-01-19  1.24   13.2   10.6     67.0    98.0    35.0  85.06  3.4    7.0
2019-01-20  1.17   13.4    6.7     61.0    98.0    20.0  84.88  2.8    6.4
2019-01-21  1.14   12.6    9.5     61.0    89.0    30.0  84.91  2.6    8.8
2019-01-22  0.97   10.4    9.0     63.0    85.0    31.0  85.17  1.3    6.4
2019-01-23  1.33   14.4   11.1     70.0    90.0    36.0  85.33  1.3   10.0
2019-01-25  1.29   14.6   11.3     59.0    94.0    28.0  85.31  1.7    9.0
2019-01-26  1.23   14.1    8.1     58.0    96.0    18.0  85.32  1.1    8.0
2019-01-27  1.05   11.8    8.2     47.0    82.0    18.0  85.23  0.9    7.6
2019-01-28  1.34   14.3   12.2     63.0    98.0    29.0  85.09  2.9    8.0

              R_s
date
2019-01-01   6.33
2019-01-02   3.97
2019-01-03   6.88
2019-01-04   7.85
2019-01-05   8.92
2019-01-06   9.33
2019-01-07   7.19
2019-01-08   8.14
2019-01-09   6.44
2019-01-10   3.56
2019-01-11   8.75
2019-01-12   8.12
2019-01-13   9.40
2019-01-14   8.39
2019-01-15   8.31
2019-01-16   6.71
2019-01-17   7.78
2019-01-18   6.32
2019-01-19   7.06
2019-01-20  11.38
2019-01-21   7.77
2019-01-22   5.24
2019-01-23   8.08
2019-01-25   8.14
2019-01-26  11.02
2019-01-27   8.57
2019-01-28   6.57