In [1]:
# import eto python library
from eto import ETo, datasets

# import pandas library
import pandas as pd

# Apagamos algunos mensajes de warning
pd.options.mode.chained_assignment = None  # default='warn'

In [2]:
# creating object from ETo class
et1 = ETo()

In [3]:
# loading path where datasets are stored
#ex1_path = datasets.get_path('example_daily')
ex1_path = '/home/adan/Documents/programacion_analisis_datos/codigos/requerimiento_agua_tomate_rojo/output/conagua_2019_febrero_req_for_et0.csv'

In [4]:
# reading example dataset
tsdata = pd.read_csv(ex1_path, parse_dates=True, infer_datetime_format=True, index_col='date')

In [5]:
tsdata.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 28 entries, 2019-02-01 to 2019-02-28
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   e_a      28 non-null     float64
 1   T_max    28 non-null     float64
 2   T_min    28 non-null     float64
 3   RH_mean  28 non-null     float64
 4   RH_max   28 non-null     float64
 5   RH_min   28 non-null     float64
 6   P        28 non-null     float64
 7   U_z      28 non-null     float64
 8   n_sun    28 non-null     float64
 9   R_s      28 non-null     float64
dtypes: float64(10)
memory usage: 2.4 KB

In [6]:
# parameters definition
# high meter sea level in meters or altitude
z_msl = 1408.99

# The latitude of the met station (dec deg) (only needed if R_s or R_n are not in df).
lat = 19.59216667

# The longitude of the met station (dec deg) (only needed if calculating ETo hourly)
lon = -103.59075

# The longitude of the center of the time zone 
# (dec deg) (only needed if calculating ETo hourly).
TZ_lon = -103

# The Pandas time frequency string of the input and output. 
# The minimum frequency is hours (H) and the maximum is month (M)
freq = 'D'

In [7]:
# loading base parameters so rest of them can be estimated automatically
et1.param_est(tsdata, freq, z_msl, lat, lon, TZ_lon)

In [8]:
# showing information about dataframe
et1.ts_param.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 28 entries, 2019-02-01 to 2019-02-28
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   e_a      28 non-null     float64
 1   T_max    28 non-null     float64
 2   T_min    28 non-null     float64
 3   RH_mean  28 non-null     float64
 4   RH_max   28 non-null     float64
 5   RH_min   28 non-null     float64
 6   P        28 non-null     float64
 7   U_z      28 non-null     float64
 8   n_sun    28 non-null     float64
 9   R_s      28 non-null     float64
 10  R_n      28 non-null     float64
 11  G        28 non-null     float64
 12  T_mean   28 non-null     float64
 13  T_dew    0 non-null      float64
 14  gamma    28 non-null     float64
 15  e_max    28 non-null     float64
 16  e_min    28 non-null     float64
 17  e_s      28 non-null     float64
 18  delta    28 non-null     float64
 19  R_a      28 non-null     float64
 20  U_2      28 non-null     float64
dtypes: float64(21)
memory usage: 4.8 KB

In [9]:
# showing dataframe head
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
et1.ts_param

,e_a,T_max,T_min,RH_mean,RH_max,RH_min,P,U_z,n_sun,R_s,...,G,T_mean,T_dew,gamma,e_max,e_min,e_s,delta,R_a,U_2
date,,,,,,,,,,,,,,,,,,,,,
2019-02-01,1.05,11.6,9.3,59.0,98.0,31.0,85.21,2.5,3.0,7.00,...,0.0,10.45,NaN,0.056665,1.365996,1.171536,1.268766,0.084489,28.850882,2.500556
2019-02-02,0.99,10.4,9.5,79.0,99.0,41.0,85.23,0.6,2.4,4.40,...,0.0,9.95,NaN,0.056678,1.261268,1.187421,1.224344,0.082041,28.979232,0.600133
2019-02-03,0.88,9.6,6.9,70.0,95.0,22.0,85.12,1.5,1.0,7.65,...,0.0,8.25,NaN,0.056605,1.195433,0.995000,1.095217,0.074163,29.109276,1.500333
2019-02-04,0.73,8.9,5.4,44.0,92.0,15.0,85.03,2.6,1.0,8.75,...,0.0,7.15,NaN,0.056545,1.140328,0.896969,1.018649,0.069417,29.240937,2.600578
2019-02-05,0.89,11.4,6.9,49.0,92.0,18.0,85.04,2.3,2.0,9.97,...,0.0,9.15,NaN,0.056552,1.348028,0.995000,1.171514,0.078249,29.374136,2.300511
2019-02-06,0.94,11.4,6.5,50.0,95.0,17.0,85.07,3.2,4.0,10.45,...,0.0,8.95,NaN,0.056572,1.348028,0.967977,1.158003,0.077324,29.508793,3.200711
2019-02-07,0.97,10.9,8.0,51.0,95.0,20.0,85.05,2.8,3.5,8.08,...,0.0,9.45,NaN,0.056558,1.304014,1.072769,1.188391,0.079653,29.644829,2.800622
2019-02-08,1.05,12.8,9.1,51.0,89.0,25.0,85.11,3.3,5.0,9.17,...,0.0,10.95,NaN,0.056598,1.478288,1.155839,1.317064,0.087000,29.782162,3.300733
2019-02-09,1.25,13.5,11.2,71.0,94.0,37.0,85.34,0.8,8.0,7.26,...,0.0,12.35,NaN,0.056751,1.547467,1.330268,1.438868,0.094371,29.920711,0.800178
2019-02-10,1.26,13.1,12.4,74.0,96.0,39.0,85.30,0.8,7.0,4.02,...,0.0,12.75,NaN,0.056724,1.507597,1.439989,1.473793,0.096573,30.060393,0.800178
2019-02-11,1.21,13.3,9.1,66.0,96.0,27.0,85.14,0.8,7.0,9.90,...,0.0,11.20,NaN,0.056618,1.527418,1.155839,1.341629,0.088279,30.201127,0.800178
2019-02-12,1.10,12.8,9.2,51.0,96.0,25.0,85.01,2.9,6.6,9.21,...,0.0,11.00,NaN,0.056532,1.478288,1.163665,1.320976,0.087255,30.342829,2.900644
2019-02-13,1.17,14.7,9.9,56.0,96.0,28.0,85.17,4.3,7.0,10.69,...,0.0,12.30,NaN,0.056638,1.672686,1.219758,1.446222,0.094099,30.485415,4.300955
2019-02-14,1.10,12.5,8.7,56.0,98.0,24.0,85.16,2.5,5.2,9.55,...,0.0,10.60,NaN,0.056631,1.449481,1.124999,1.287240,0.085236,30.628803,2.500556
2019-02-15,1.00,12.0,8.3,50.0,98.0,21.0,85.05,1.8,5.0,9.47,...,0.0,10.15,NaN,0.056558,1.402564,1.094886,1.248725,0.083013,30.772908,1.800400
2019-02-16,1.10,12.1,9.7,71.0,98.0,30.0,85.04,1.8,5.2,7.66,...,0.0,10.90,NaN,0.056552,1.411839,1.203494,1.307666,0.086746,30.917647,1.800400
2019-02-17,1.06,11.9,8.7,67.0,96.0,26.0,85.13,1.0,5.0,8.89,...,0.0,10.30,NaN,0.056611,1.393342,1.124999,1.259171,0.083748,31.062936,1.000222
2019-02-18,1.05,11.5,9.4,59.0,98.0,25.0,85.10,3.2,4.0,7.24,...,0.0,10.45,NaN,0.056591,1.356986,1.179455,1.268220,0.084489,31.208691,3.200711
2019-02-19,1.24,13.2,10.6,67.0,98.0,35.0,85.06,3.4,7.0,8.09,...,0.0,11.90,NaN,0.056565,1.517479,1.278216,1.397847,0.091946,31.354829,3.400755
2019-02-20,1.17,13.4,6.7,61.0,98.0,20.0,84.88,2.8,6.4,13.05,...,0.0,10.05,NaN,0.056445,1.537414,0.981407,1.259410,0.082525,31.501266,2.800622
2019-02-21,1.14,12.6,9.5,61.0,89.0,30.0,84.91,2.6,8.8,8.92,...,0.0,11.05,NaN,0.056465,1.459028,1.187421,1.323224,0.087510,31.647919,2.600578
2019-02-22,0.97,10.4,9.0,63.0,85.0,31.0,85.17,2.6,6.4,6.02,...,0.0,9.70,NaN,0.056638,1.261268,1.148060,1.204664,0.080839,31.794705,2.600578
2019-02-23,1.33,14.4,11.1,70.0,90.0,36.0,85.33,1.3,10.0,9.28,...,0.0,12.75,NaN,0.056744,1.640576,1.321465,1.481021,0.096573,31.941542,1.300289
2019-02-24,1.33,14.4,11.1,70.0,90.0,36.0,85.33,1.3,10.0,9.33,...,0.0,12.75,NaN,0.056744,1.640576,1.321465,1.481021,0.096573,32.088349,1.300289
2019-02-25,1.29,14.6,11.3,59.0,94.0,28.0,85.31,1.7,9.0,9.37,...,0.0,12.95,NaN,0.056731,1.661922,1.339122,1.500522,0.097690,32.235044,1.700378
2019-02-26,1.23,14.1,8.1,58.0,96.0,18.0,85.32,1.1,8.0,12.69,...,0.0,11.10,NaN,0.056738,1.609008,1.080097,1.344553,0.087766,32.381547,1.100244
2019-02-27,1.05,11.8,8.2,47.0,82.0,18.0,85.23,0.9,7.6,9.87,...,0.0,10.00,NaN,0.056678,1.384174,1.087469,1.235822,0.082283,32.527778,0.900200
2019-02-28,1.34,14.3,12.2,63.0,98.0,29.0,85.09,2.9,8.0,7.58,...,0.0,13.25,NaN,0.056585,1.629994,1.421168,1.525581,0.099386,32.673659,2.900644

In [10]:

#et1.ts_param["R_s"].loc['2000-01-01']

In [11]:
# calculating evapotranspiration reference ETo
eto1 = et1.eto_fao()

In [12]:
# showing et0 head
eto1.head()

date
2019-02-01    1.42
2019-02-02    1.05
2019-02-03    1.35
2019-02-04    1.68
2019-02-05    1.75
Name: ETo_FAO_mm, dtype: float64

In [13]:
# showing et0 info
display(eto1)

date
2019-02-01    1.42
2019-02-02    1.05
2019-02-03    1.35
2019-02-04    1.68
2019-02-05    1.75
2019-02-06    1.67
2019-02-07    1.51
2019-02-08    1.78
2019-02-09    1.36
2019-02-10    1.07
2019-02-11    1.54
2019-02-12    1.65
2019-02-13    2.00
2019-02-14    1.57
2019-02-15    1.65
2019-02-16    1.45
2019-02-17    1.50
2019-02-18    1.51
2019-02-19    1.44
2019-02-20    1.61
2019-02-21    1.55
2019-02-22    1.43
2019-02-23    1.58
2019-02-24    1.58
2019-02-25    1.68
2019-02-26    1.83
2019-02-27    1.59
2019-02-28    1.51
Name: ETo_FAO_mm, dtype: float64